version: '3.8'

services:
  app:
    build: .
    container_name: shop_final_fixed
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      # Локальная база -> База внутри папки app в контейнере
      - ./app/shop.db:/app_root/app/shop.db
    restart: always
